export type Language = 'en' | 'es' | 'hi' | 'fr';

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    app_name: 'Grain Vision',
    home: 'Home',
    scan: 'Scan',
    history: 'History',
    settings: 'Settings',
    tagline: 'ML-Powered Grain Identification',
    tap_to_scan: 'Tap to Scan',
    scan_sub: 'Identify grain types in seconds',
    recent_scans: 'Recent Scans',
    grain_library: 'Grain Library',
    search_placeholder: 'Search grains...',
    confidence: 'Confidence',
    read_aloud: 'Read Aloud',
    save_scan: 'Save to History',
    view_details: 'View Grain Details',
    calories: 'Calories',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Fat',
    fiber: 'Fiber',
    overview: 'Overview',
    cultivation: 'Cultivation',
    uses: 'Culinary Uses',
    no_history: 'No scan history yet.',
    clear_history: 'Clear Local History',
    theme: 'Theme Settings',
    dark_mode: 'Dark Mode',
    offline_mode: 'Offline Prediction',
    offline_mode_sub: 'Analyze locally without internet',
    language: 'App Language',
    server_status: 'API Server Status',
    connected: 'Connected',
    disconnected: 'Using Offline Simulator',
    server_address: 'Server Address',
    accuracy_dashboard: 'Accuracy Analytics',
    average_acc: 'Average Accuracy',
    total_analyzed: 'Total Scans',
    distribution: 'Distribution',
    select_source: 'Choose Image Source',
    camera: 'Take a Photo',
    gallery: 'Choose from Gallery',
    cancel: 'Cancel',
    analyzing: 'Analyzing Grain Image...',
    success: 'Classification Successful',
    error: 'Error identifying grain. Try again.',
    no_details: 'No grain profile details found.',
    delete_scan: 'Delete Scan',
    sure_delete: 'Delete this scan from history?',
    yes: 'Yes',
    no: 'No'
  },
  es: {
    app_name: 'Grain Vision',
    home: 'Inicio',
    scan: 'Escanear',
    history: 'Historial',
    settings: 'Ajustes',
    tagline: 'Identificación de Granos por IA',
    tap_to_scan: 'Toca para Escanear',
    scan_sub: 'Identifica tipos de granos al instante',
    recent_scans: 'Escaneos Recientes',
    grain_library: 'Biblioteca de Granos',
    search_placeholder: 'Buscar granos...',
    confidence: 'Confianza',
    read_aloud: 'Leer en voz alta',
    save_scan: 'Guardar en Historial',
    view_details: 'Ver Detalles del Grano',
    calories: 'Calorías',
    protein: 'Proteínas',
    carbs: 'Carbohidratos',
    fat: 'Grasas',
    fiber: 'Fibra',
    overview: 'Resumen',
    cultivation: 'Cultivo',
    uses: 'Usos Culinarios',
    no_history: 'Aún no hay historial de escaneos.',
    clear_history: 'Limpiar Historial Local',
    theme: 'Configuración del Tema',
    dark_mode: 'Modo Oscuro',
    offline_mode: 'Predicción Sin Conexión',
    offline_mode_sub: 'Analiza localmente sin internet',
    language: 'Idioma de la App',
    server_status: 'Estado del Servidor API',
    connected: 'Conectado',
    disconnected: 'Usando Simulador Local',
    server_address: 'Dirección del Servidor',
    accuracy_dashboard: 'Análisis de Precisión',
    average_acc: 'Precisión Promedio',
    total_analyzed: 'Escaneos Totales',
    distribution: 'Distribución',
    select_source: 'Seleccionar Origen',
    camera: 'Tomar una Foto',
    gallery: 'Elegir de la Galería',
    cancel: 'Cancelar',
    analyzing: 'Analizando Imagen...',
    success: 'Clasificación Exitosa',
    error: 'Error al identificar. Inténtelo de nuevo.',
    no_details: 'No se encontraron detalles del grano.',
    delete_scan: 'Eliminar Escaneo',
    sure_delete: '¿Eliminar este escaneo del historial?',
    yes: 'Sí',
    no: 'No'
  },
  hi: {
    app_name: 'ग्रेन विजन (Grain Vision)',
    home: 'होम',
    scan: 'स्कैन',
    history: 'इतिहास',
    settings: 'सेटिंग्स',
    tagline: 'मशीन लर्निंग आधारित अनाज पहचान',
    tap_to_scan: 'स्कैन करने के लिए टैप करें',
    scan_sub: 'कुछ ही सेकंड में अनाज के प्रकार पहचानें',
    recent_scans: 'हाल के स्कैन',
    grain_library: 'अनाज लाइब्रेरी',
    search_placeholder: 'अनाज खोजें...',
    confidence: 'सटीकता विश्वास',
    read_aloud: 'बोलकर सुनाएं',
    save_scan: 'इतिहास में सहेजें',
    view_details: 'अनाज का विवरण देखें',
    calories: 'कैलोरी',
    protein: 'प्रोटीन',
    carbs: 'कार्ब्स',
    fat: 'वसा',
    fiber: 'फाइबर',
    overview: 'विवरण',
    cultivation: 'खेती की जानकारी',
    uses: 'रसोई में उपयोग',
    no_history: 'अभी तक कोई इतिहास नहीं है।',
    clear_history: 'स्थानीय इतिहास साफ करें',
    theme: 'थीम सेटिंग्स',
    dark_mode: 'डार्क मोड',
    offline_mode: 'ऑफ़लाइन भविष्यवाणी',
    offline_mode_sub: 'इंटरनेट के बिना स्थानीय रूप से विश्लेषण करें',
    language: 'ऐप की भाषा',
    server_status: 'सर्वर की स्थिति',
    connected: 'कनेक्टेड',
    disconnected: 'ऑफ़लाइन सिम्युलेटर चालू',
    server_address: 'सर्वर एड्रेस',
    accuracy_dashboard: 'सटीकता विश्लेषण',
    average_acc: 'औसत सटीकता',
    total_analyzed: 'कुल स्कैन',
    distribution: 'अनाज वितरण',
    select_source: 'छवि स्रोत चुनें',
    camera: 'फ़ोटो लें',
    gallery: 'गैलरी से चुनें',
    cancel: 'रद्द करें',
    analyzing: 'अनाज का विश्लेषण किया जा रहा है...',
    success: 'सफलतापूर्वक पहचान लिया गया',
    error: 'पहचानने में असमर्थ। पुनः प्रयास करें।',
    no_details: 'कोई विवरण नहीं मिला।',
    delete_scan: 'स्कैन हटाएं',
    sure_delete: 'क्या आप इस स्कैन को इतिहास से हटाना चाहते हैं?',
    yes: 'हाँ',
    no: 'नहीं'
  },
  fr: {
    app_name: 'Grain Vision',
    home: 'Accueil',
    scan: 'Scanner',
    history: 'Historique',
    settings: 'Paramètres',
    tagline: 'Identification de Grains par IA',
    tap_to_scan: 'Appuyer pour Scanner',
    scan_sub: 'Identifiez les grains en quelques secondes',
    recent_scans: 'Analyses Récentes',
    grain_library: 'Bibliothèque de Grains',
    search_placeholder: 'Rechercher des grains...',
    confidence: 'Confiance',
    read_aloud: 'Lire à Haute Voix',
    save_scan: 'Sauvegarder',
    view_details: 'Voir les détails du grain',
    calories: 'Calories',
    protein: 'Protéines',
    carbs: 'Glucides',
    fat: 'Lipides',
    fiber: 'Fibres',
    overview: 'Aperçu',
    cultivation: 'Culture',
    uses: 'Usage Culinaire',
    no_history: 'Aucun historique pour le moment.',
    clear_history: 'Effacer l\'historique local',
    theme: 'Paramètres du Thème',
    dark_mode: 'Mode Sombre',
    offline_mode: 'Prédiction Hors Ligne',
    offline_mode_sub: 'Analyser localement sans internet',
    language: 'Langue de l\'application',
    server_status: 'Statut du Serveur API',
    connected: 'Connecté',
    disconnected: 'Utilisation du Simulateur',
    server_address: 'Adresse du Serveur',
    accuracy_dashboard: 'Analyses de Précision',
    average_acc: 'Précision Moyenne',
    total_analyzed: 'Total des Analyses',
    distribution: 'Distribution',
    select_source: 'Choisir la source',
    camera: 'Prendre une photo',
    gallery: 'Choisir depuis la galerie',
    cancel: 'Annuler',
    analyzing: 'Analyse de l\'image en cours...',
    success: 'Classification réussie',
    error: 'Erreur d\'identification. Réessayez.',
    no_details: 'Aucun détail de grain trouvé.',
    delete_scan: 'Supprimer l\'analyse',
    sure_delete: 'Supprimer cette analyse de l\'historique?',
    yes: 'Oui',
    no: 'Non'
  }
};
